### ISSUE TITLE
Difference between Inputformat, Algorithmusparameter, Ausgabeformat

### ISSUE THREAD

**Issue by salmma** [PlanQK/platform#26]
Not clear what the difference between Inputformat and Algorithmusparameter is. In addition, description of Algorithmusparameter and Ausgabeformat is the same (see screenshot)

**To Reproduce**
1. Go to Algorithm --> Details

**Screenshots**
<img width="345" alt="Bildschirmfoto 2021-01-21 um 19 53 25" src="https://user-images.githubusercontent.com/23473511/105398299-79f9f580-5c22-11eb-987b-14d03301dd95.png">

**Desktop (please complete the following information):**
 - OS: macos big sur
- Browser: Safari
- Version 14.0.2

**Comment by miwurster** [comment]
We updated the placeholder texts to clarify the usage of those fields.
