### ISSUE TITLE
Implement spellchecker into input fields.

### ISSUE THREAD

**Issue by jmreiner** [PlanQK/platform#30]
Ok, so usually input fields in a browser have a spellchecker integrated (e.g., when entering something here in the comment field on Github). For some reason, this is not the case for me when editing any content in the PlanQK platform (neither in Chrome nor in Firefox). This is kinda annoying, because since this is so prevalent nowadays I actually got quite used to that.

It might also be that it is annoying when entering latex code and so on. I am not sure how sophisticated these checkers can be (i.e. ignore stuff between double dollars), of if one could make it an option to toggle it.

**Comment by radufalcusanStoneone** [comment]
Thank you for the feedback, the spell checker has been integrated!
