### ISSUE TITLE
Enable metadata annotation for implementations

### ISSUE THREAD

**Issue by mdafokus** [PlanQK/platform#66]
Allow user to annotate implementations with following metadata:  

- [x] problem type: https://gitlab.fokus.fraunhofer.de/tsforplanqk/ts-planqk-docker/-/blob/main/extracted%20knowledge/ProblemTypes.json
- [x] programming language: https://github.com/PlanQK/semantic-services/blob/master/extracted%20knowledge/ProgrammingLanguages_List.json 
- [x] Quantum computation model (1:1): https://github.com/PlanQK/semantic-services/blob/master/extracted%20knowledge/QuantumComputationModels.json  (add inference from algorithm in the semantic component)
- [x] software tool (sdk/framework/library/api): https://github.com/PlanQK/semantic-services/blob/master/extracted%20knowledge/SoftwareTool_List.json
- [x] license: https://github.com/PlanQK/semantic-services/blob/master/extracted%20knowledge/Licenses_List.json
- [x] Learning Methods

**Comment by radufalcusanStoneone** [comment]
The taxonomies have been added to the implementation
