### ISSUE TITLE
Enable metadata annotation for data pools

### ISSUE THREAD

**Issue by mdafokus** [PlanQK/platform#67]
Allow user to annotate **data pools** with following metadata:

- [x]  license: https://github.com/PlanQK/semantic-services/blob/master/extracted%20knowledge/Licenses_List.json
- [x]  labelled: true/false 
- [x] format: https://gitlab.fokus.fraunhofer.de/tsforplanqk/ts-planqk-docker/-/blob/main/extracted%20knowledge/DatapoolFormats.json
- [x] problem types: https://gitlab.fokus.fraunhofer.de/tsforplanqk/ts-planqk-docker/-/blob/main/extracted%20knowledge/ProblemTypes.json
- [x] industries: https://gitlab.fokus.fraunhofer.de/tsforplanqk/ts-planqk-docker/-/blob/main/extracted%20knowledge/Industries.json

**Comment by radufalcusanStoneone** [comment]
The taxonomies have been added to the data pools
