### ISSUE TITLE
Invitation to an organization: HTTP Error 401

### ISSUE THREAD

**Issue by mar-be** [PlanQK/platform#70]
**Current Behavior**
  When I send an invitation to my organization to users of the PlanQK platform, some of them cannot accept this invitation due to an HTTP Error 401. The error occurs after the user has clicked on the invitation link in the email and after he has logged in successfully. However, not every user seems to be affected by this error. Some users can successfully join the organization via the invitation link. Deleting and re-inviting the affected users did not help.
  
  **Steps to Reproduce**
  1. Create an organization
  2. Add members
  3. Click on the invitation link in the sent email
  
  **Expected Behavior**
  All users can join the organization via their invitation link from their email.
  
  **Desktop (please complete the following information):**
   - OS: Windows/macOS
   - Browser: the invited users have used different browsers

**Comment by ckrieger** [comment]
Hey @mar-be , thanks for your help. We fixed this issue in our current release.
