### ISSUE TITLE
Relation to other Algorithms does not save long "Detailed description of relation" (without warning)

### ISSUE THREAD

**Issue by Danielle-Schuman** [PlanQK/platform#71]
**Current Behavior**
If one puts a "detailed description of relation" that is too long, the relation will either not be saved at all, or, for an existing relation, the new description will not be saved. However, no error message / warning about the text being too long is shown.

**Steps to Reproduce**
1. Go to an Algorithm description.
2. Click on '+' next to Relations to other Algorithms. A pop-up opens up.
3. In the pop-up, scroll down to 'Detailed description of relation'.
4. Paste quite some lines of text in the corresponding field. E.g. I used the following: "To train Quantum Boltzmann Machines, one needs to repeatedly sample the Boltzmann distributed states of their neurons being “on” or “off”, where the respective distribution depends on the QBM's current weights and biases. This sampling has to be performed several times for both the case where the QBM's visual neurons are clamped to the current input of the QBM as well as the case where they are not. It can be performed efficiently by minimizing the QBM's energy function on a Quantum Annealer for both cases, as the possible solutions returned by the Annealer are approxiametly Boltzmann distributed."
5. Click on "Save", the pop-up closes.
6. The relation does not show up in the relations section.

Alternatively:
1. Go to an Algorithm description.
2. Click on '+' next to Relations to other Algorithms.
3. In the pop-up, scroll down to 'Detailed description of relation'.
4. Paste a short text in the corresponding field. E.g. I used the following: "Test123". Alternatively, you can also use no text.
5. Click on "Save", pop-up closes.
6. The relation does show up in the relations section.
7. Click on "Edit" (the pencil-icon) next to the relation.
8. Paste some lines of text (example see above).
9. Click "Save".
10. Click on "Edit" next to the relation again. Observe that it still shows the old, short text (or no text) in the field 'Detailed description of relation' of the pop-up, and not the text you just added.

**Expected Behavior**
Three options:
1. After adding the long text (multiple lines), this will be saved and visible when clicking / hovering over the relation.
2. When adding a text that is too long to be saved (/ displayed with hovering?), I get an error message either upon entering the text or upon tryiong to save, telling me the text is too long by X characters and needs to be shortened, the Pop-Up stays open to let me do that and try saving again.
3. It is simply not possible to input a text this long into the corresponding field, the text will be cut off after the maximum number of characters that can be saved and this will be visible in the Pop-Up when writing / after pasting.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox, Version 103.0.1

**Comment by miwurster** [comment]
We fixed the issue with one of our latest releases. Users can now enter a description up to 255 characters.
