### ISSUE TITLE
No Owner for qAI Apps of Organizations 

### ISSUE THREAD

**Issue by lharzenetter** [PlanQK/platform#72]
**Current Behavior**
If I upload a qAI app in the context of an organization the `Owner` field stays empty.

**Steps to Reproduce**
1. Go to qAI Apps
2. Click on QHAna
3. See the missing `Owner` field

**Expected Behavior**
The owner should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/23058331/187219564-5dd1af04-ee56-4738-82a8-4a2ac5e87940.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Comment by radufalcusanStoneone** [comment]
Thank you for your feedback. This issue has been fixed and released.
