### ISSUE TITLE
Classical algorithm has the property "Quantum Computation Models" what is semantically wrong

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#74]
**Current Behavior**
User can specify a "quantum computation model" for a classical algorithm. It is semantically wrong, the algorithm should have in this case the type "hybrid".  

**Steps to Reproduce**
1. Go to 'Algorithms'
2. Click on 'Add Algorithm' -> Type "Classic"
4. See the field "Quantum Computation Models"

**Expected Behavior**
No field "Quantum Computation Models" in descriptions of classical algorithms.

**Comment by miwurster** [comment]
Fixed and released.
