### ISSUE TITLE
Impossible to confirm publishing of old (?) algorithms under CC BY 4.0 as algorithm owner

### ISSUE THREAD

**Issue by Danielle-Schuman** [PlanQK/platform#76]
**Current Behavior**
On the site of an algorithm, in the tab "Community" it says: "One of the owner must confirm that the knowledge artifact will be published under the CC BY 4.0" but there is no obvious way to give this confirmation.

**Steps to Reproduce**
1. Go to algorithm you are the owner of (might need to have been created before the site went public).
2. Click on tab 'Commuinty'.
4. See message

**Expected Behavior**
There ought to be a tick-box / button / etc. available in the Community-Tab to confirm this. (Or, if confirmation is assumed when publishing, the message should be rephrased to something like "By publishing this knowledge artifact, the owner gives the permission to publish it under the CC BY 4.0").

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by radufalcusanStoneone** [comment]
Thank you for your feedback. We have changed the message.
