### ISSUE TITLE
Extend the metadata sended in the payload for the entity "UseCase"

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#78]
```
{
  "id": "x",
  "name": "x",
  "shortDescription": "x,",
  "description": "x",
  "approach": null (?)
  "status": "INITIAL"
}
```

Hovewer, there is more useful information about a use case on the plattform available: application areas, industries, related algorithms, implementations and datapools.  Please, provide this metadata also in the payload.

**Comment by miwurster** [comment]
Hello @mdafokus, once we use the new json-based taxonomy style for use cases we will include the information into the event message (similar to what you already know for algorithms).

Further, we will also include a list of IDs for related algorithms, impls, data pools, qai apps, and planqk services.

**Comment by miwurster** [comment]
We've included now all the information you mentioned into use case events. However, it is not released yet. We'll try to release it in the next days.

**Comment by miwurster** [comment]
The fix has been released.
