### ISSUE TITLE
Pub/Sub message on the use case delete is missing. 

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#79]
**Current Behavior**
When a user delete a use case, no message is coming to the semantic component. 

**Steps to Reproduce**
1. Go to 'Community'->  'Use Cases'
2. Click on 'Add new Use Case'
3. Delete the created Use Case
5. See error: No message is sended to the semantic component.

**Comment by radufalcusanStoneone** [comment]
The fix has been released!
