### ISSUE TITLE
Add attribute "entityMaturity" for the implementation and data pools metadata 

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#80]
**Description**
On the plattform, implementations and data pools has the attribut "Maturity". Hovewer, in contrast to algorithms, this metadata for implementations and data pools  is not sended on the semantic component.   

**Proposed Solution**
Similar to the algorithms, send the attribute "entityMaturity" with the topic message for implementations and data pools.  

**Additional Context**
This data could be useful for content filtering and ranking.

**Comment by radufalcusanStoneone** [comment]
The entityMaturity field was added to data pool and implementation topics.
