### ISSUE TITLE
Unable to delete a published algorithm

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#82]
**Current Behavior**
I created an algorithm (an example, https://platform.planqk.de/algorithms/c102cbfc-7c8c-405b-aa35-35a64b02c931/) and published it in order to test the review feature. Now I would like to delete this algorithm and can not do it. If I push on th "..." button on the right side, only the option "Report" appears.  

**Steps to Reproduce**
1. Go to 'Algorithms'
2. Click on 'Add algorithm', fill the information about the algorithm and save it.
3. Go to the tab 'Community' and publish the algorithm.
4. Try to remove or unpublish the algorithm - is not possible.

**Expected Behavior**
The user can unpublish and delete the algorithm.

**Screenshots**
![image](https://user-images.githubusercontent.com/63393143/208955352-7f886a40-9306-44e1-8540-c7f86e793eb2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 108.0.5359.125

**Comment by miwurster** [comment]
Hello @mdafokus, this is not a bug, it's actually a feature. It is also stated in the UI when trying to publish a community artifact: "Note: After an artifact has been published to the community, it cannot change its visibility back to 'private' status and cannot be deleted anymore."

In such cases, to delete an "unwanted" published artifact, please contact <support@planqk.de> and the PlanQK Administrator will downgrade artifact back to "private".
