### ISSUE TITLE
Fields with null value are removed from Input Data 

### ISSUE THREAD

**Issue by fredericschulz** [PlanQK/platform#84]
**Current Behavior**
When creating a job, input data may be provided  in form of a json document. Any keys which have the value null are removed from that document. This may lead to unexpected results in the requested service if the service expects keys to exist on its json input. That the keys are removed can be observed after creating the job by reviewing the details of that job from the job overview.

**Steps to Reproduce**
1. Create a new job
2. Provide a json document as input data that has a field with a value of null, eg. `{"nullable": null, "non_nullable": "something"}`

**Expected Behavior**
After job creation when the details are shown, the input data should match
`{"nullable": null, "non_nullable": "something"}`, instead `{"non_nullable": "something"}` is shown.

**Additional context**
May also apply to the provided job parameters.

**Comment by miwurster** [comment]
Thanks for your feedback. The fix has already been implemented and will be released the next days.

**Comment by miwurster** [comment]
Released today ;-)
