### ISSUE TITLE
Unauthenticated users unable to apply filters in advanced search

### ISSUE THREAD

**Issue by darya-mart** [PlanQK/platform#85]
**Current Behavior**
Error 401 is raised when an unauthenticated users tries to apply filter on algorithms, e.g. "Design Type".

**Steps to Reproduce**
1. Log out. 
2. Go to ['algorithms'](https://platform.planqk.de/algorithms)
3. Click on the funnel sign to apply a filter. 
4. Select any filter value, e.g.,  'Hybrid' in `Design Type` filter.
5. See 401 error. 

**Expected Behavior**
Also unauthenticated users can use faceted search since they can access some content.

**Comment by falcusanradu** [comment]
This issue has been fixed and released

**Comment by radufalcusanStoneone** [comment]
This issue has been fixed and released
